version: '3'

networks:
  1panel-network:
    external: true

services:
  mysql:
    image: mysql:5.6.51
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PANEL_DB_ROOT_PASSWORD}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3306
    volumes:
      - ${MYSQL_ROOT_PATH}/data/:/var/lib/mysql
      - ${MYSQL_ROOT_PATH}/conf/my.cnf:/etc/mysql/my.cnf
      - ${MYSQL_ROOT_PATH}/log:/var/log/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    labels:
      createdBy: "Apps"
