version: '3'

networks:
  1panel-network:
    external: true

services:
  onedev:
    image: 1dev/server:10.3.1
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6610"
      - "${PANEL_APP_PORT_SSH}:6611"
    volumes:
      - ${ONEDEV_ROOT_PATH}/data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    labels:
      createdBy: "Apps"
