version: "3.8"

networks:
  1panel-network:
    external: true

services:
  iyuuplus:
    image: iyuucn/iyuuplus-dev:latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8787
    volumes:
      - ${IYUUCN_ROOT_PATH}/db:/IYUU/db
      - ${IYUUCN_ROOT_PATH}/bt/qBittorrent:/qBittorrent
      - ${IYUUCN_ROOT_PATH}/bt/transmission:/transmission
