version: "3"

networks:
  1panel-network:
    external: true

services:
  bark:
    image: finab/bark-server:v2.1.5
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    volumes:
      - ${BARK_ROOT_PATH}/data:/data
    environment:
      BARK_SERVER_ADDRESS: ${BARK_SERVER_ADDRESS:-0.0.0.0:8080}
      BARK_SERVER_URL_PREFIX: ${BARK_SERVER_URL_PREFIX:-/}
      BARK_SERVER_DATA_DIR: ${BARK_SERVER_DATA_DIR:-/data}
      BARK_SERVER_DSN: ${BARK_SERVER_DSN:-}
      BARK_SERVER_SERVERLESS: false
      BARK_SERVER_BASIC_AUTH_USER: ${BARK_SERVER_BASIC_AUTH_USER:-}
      BARK_SERVER_BASIC_AUTH_PASSWORD: ${BARK_SERVER_BASIC_AUTH_PASSWORD:-}
