version: "3"

networks:
  1panel-network:
    external: true

services:
  mysql:
    image: mysql:8.4.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    environment:
      MYSQL_ROOT_PASSWORD: ${PANEL_DB_ROOT_PASSWORD}
    ports:
      - ${PANEL_APP_PORT_HTTP}:3306
    volumes:
      - ${MYSQL_ROOT_PATH}/data:/var/lib/mysql
      - ${MYSQL_ROOT_PATH}/conf/my.cnf:/etc/my.cnf
      - ${MYSQL_ROOT_PATH}/log:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --default-authentication-plugin=mysql_native_password
