version: "3"

networks:
  1panel-network:
    external: true

services:
  mariadb:
    image: mariadb:10.11.8
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3306
    volumes:
      - ${MARIADB_ROOT_PATH}/data:/var/lib/mysql
      - ${MARIADB_ROOT_PATH}/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${PANEL_DB_ROOT_PASSWORD}
