version: "3.7"

networks:
  1panel-network:
    external: true

services:
  stream-rec-backend:
    image: streamrec/stream-rec:latest
    container_name: stream-rec
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_API:-12555}:12555
    volumes:
      - ${STREAM_REC_ROOT_PATH}/records:/opt/records
      - ${STREAM_REC_ROOT_PATH}/download:/download
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - LOG_LEVEL=INFO
      - DB_PATH=/opt/records
      - JWT_SECRET=${REC_JWT_SECRET}
      - LOGIN_SECRET=${REC_LOGIN_SECRET}

  stream-rec-frontend:
    depends_on:
      - stream-rec-backend
    image: streamrec/stream-rec-front:latest
    container_name: stream-rec-frontend
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP:-15275}:15275
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - API_URL=${REC_API_URL}
      - NEXTAUTH_SECRET=${REC_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${REC_NEXTAUTH_URL}
      - WS_API_URL=${REC_WS_API_URL}
