version: '3.8'
networks:
  1panel-network:
    external: true
services:
  alist:
    image: xhofe/alist:v3.35.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5244
    volumes:
      - ${ALIST_ROOT_PATH}/data:/opt/alist/data
    env_file:
      - ./custom.env
