version: '3.3'

networks:
  1panel-network:
    external: true

services:
  alist:
    image: ${OS_VERSION}
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5244
    volumes:
      - ${ALIST_ROOT_PATH}/data:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
