blank_issues_enabled: false
contact_links:
  - name: 博客论坛
    url: https://blog.lifebus.top/
    about: 总能找到你想要的
  - name: 萌森工作室
    url: https://www.tianyancha.com/company/6145984989
    about: 新疆萌森软件开发工作室提供技术支持
