version: "3.8"

networks:
  1panel-network:
    external: true

services:
  movie-pilot:
    image: jxxghp/moviepilot:1.9.7
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
      - ${PANEL_APP_PORT_API}:3001
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${MOVIEPILOT_ROOT_PATH}/config:/config
      - ${MOVIEPILOT_ROOT_PATH}/moviepilot:/moviepilot
      - ${MOVIEPILOT_ROOT_PATH}/download:/download
      - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
      - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
      - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
    environment:
      - TZ=Asia/Shanghai
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - UMASK=${UMASK:-022}
      - PROXY_HOST=${PROXY_HOST:-}
      - MOVIEPILOT_AUTO_UPDATE=${MOVIEPILOT_AUTO_UPDATE:-false}
      - SUPERUSER=${SUPERUSER:-admin}
      - API_TOKEN=${API_TOKEN:-moviepilot}
      - AUTO_UPDATE_RESOURCES=${AUTO_UPDATE_RESOURCES:-false}
      - IYUU_SIGN=${IYUU_SIGN:-}
    logging:
      driver: json-file
      options:
        max-size: 5m
    env_file:
      - ./data/moviepilot.env
      - .env
