version: "3"

networks:
  1panel-network:
    external: true

services:
  bark:
    image: zerotier/zerotier:1.12.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    network_mode: ${NETWORK_MODE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:9993
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - ZEROTIER_API_SECRET=${ZEROTIER_API_SECRET:-}
      - ZEROTIER_IDENTITY_PUBLIC=${ZEROTIER_IDENTITY_PUBLIC:-}
      - ZEROTIER_IDENTITY_SECRET=${ZEROTIER_IDENTITY_SECRET:-}
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    command:
      - /bin/bash
      - ${NETWORK_ID}
