version: "3"

networks:
  1panel-network:
    external: true

services:
  redis:
    image: redis:6.2.14
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6379
    command: redis-server  /etc/redis/redis.conf --loglevel warning --requirepass ${PANEL_REDIS_ROOT_PASSWORD}
    volumes:
      - ${REDIS_ROOT_PATH}/data:/data
      - ${REDIS_ROOT_PATH}/conf/redis.conf:/etc/redis/redis.conf
      - ${REDIS_ROOT_PATH}/logs:/logs
