version: "3"

networks:
  1panel-network:
    external: true

services:
  emby:
    image: lovechen/embyserver:4.8.0.21
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    network_mode: ${NETWORK_MODE}
    environment:
      - UID=${UID}
      - GID=${GID}
      - GIDLIST=${GIDLIST}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ${EMBY_ROOT_PATH}/config:/config
      - ${EMBY_ROOT_PATH}/config/config/system.xml:/config/config/system.xml
      - ${EMBY_ROOT_PATH}/mnt:/mnt
      - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
      - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
      - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
      - ${PANEL_APP_PORT_HTTPS}:${PANEL_APP_PORT_HTTPS}
      - 1900:1900/udp
      - 7359:7359/udp
    devices:
      - ${EMBY_DRIVE_PATH}:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
