version: "3.2"

networks:
  1panel-network:
    external: true

services:
  outline:
    image: outlinewiki/outline:0.76.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    env_file: outline.env
    ports:
      - ${PANEL_APP_PORT_HTTP-3000}:${PANEL_APP_PORT_HTTP-3000}
    environment:
      APP_NAME: ${APP_NAME:-Outline}
      NODE_ENV: production
      FORCE_HTTPS: false
      ENABLE_UPDATES: false
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-zh_CN}
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      PGSSLMODE: ${PGSSLMODE:-disable}
      REDIS_URL: ${REDIS_URL}
      URL: ${URL:-}
      PORT: ${PANEL_APP_PORT_HTTP:-3000}
      FILE_STORAGE: ${FILE_STORAGE:-local}
      FILE_STORAGE_LOCAL_ROOT_DIR: ${FILE_STORAGE_LOCAL_ROOT_DIR:-/var/lib/outline/data}
      FILE_STORAGE_UPLOAD_MAX_SIZE: ${FILE_STORAGE_UPLOAD_MAX_SIZE:-262144000}
      FILE_STORAGE_IMPORT_MAX_SIZE: ${FILE_STORAGE_IMPORT_MAX_SIZE:-}
      FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE: ${FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_REGION: ${AWS_REGION:-}
      AWS_S3_ACCELERATE_URL: ${AWS_S3_ACCELERATE_URL:-}
      AWS_S3_UPLOAD_BUCKET_URL: ${AWS_S3_UPLOAD_BUCKET_URL:-}
      AWS_S3_UPLOAD_BUCKET_NAME: ${AWS_S3_UPLOAD_BUCKET_NAME:-}
      AWS_S3_FORCE_PATH_STYLE: ${AWS_S3_FORCE_PATH_STYLE:-true}
      AWS_S3_ACL: ${AWS_S3_ACL:-private}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID:-}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET:-}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET:-}
      AZURE_RESOURCE_APP_ID: ${AZURE_RESOURCE_APP_ID:-}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
      GITHUB_APP_ID: ${GITHUB_APP_ID:-}
      GITHUB_APP_NAME: ${GITHUB_APP_NAME:-}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY:-}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:-}
      OIDC_AUTH_URI: ${OIDC_AUTH_URI:-}
      OIDC_TOKEN_URI: ${OIDC_TOKEN_URI:-}
      OIDC_USERINFO_URI: ${OIDC_USERINFO_URI:-}
      OIDC_LOGOUT_URI: ${OIDC_LOGOUT_URI:-}
      OIDC_USERNAME_CLAIM: ${OIDC_USERNAME_CLAIM:-preferred_username}
      OIDC_DISPLAY_NAME: ${OIDC_DISPLAY_NAME:-OpenID}
      OIDC_SCOPES: ${OIDC_SCOPES:-openid profile email}
      CDN_URL: ${CDN_URL:-}
      SLACK_VERIFICATION_TOKEN: ${SLACK_VERIFICATION_TOKEN:-}
      SLACK_APP_ID: ${SLACK_APP_ID:-}
      SLACK_MESSAGE_ACTIONS: ${SLACK_MESSAGE_ACTIONS:-}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-}
      SMTP_REPLY_EMAIL: ${SMTP_REPLY_EMAIL:-}
      SMTP_TLS_CIPHERS: ${SMTP_TLS_CIPHERS:-TLSv1.2}
      SMTP_SECURE: ${SMTP_SECURE:-true}
      IFRAMELY_URL: ${IFRAMELY_URL:-http://127.0.0.1}
      IFRAMELY_API_KEY: ${IFRAMELY_API_KEY:-}
    volumes:
      - ${OUTLINE_ROOT_PATH}/data:/var/lib/outline/data
