version: "3.9"

networks:
  1panel-network:
    external: true

services:
  siyuan:
    image: b3log/siyuan:v3.0.13
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    command: [ '--workspace=/siyuan/workspace/', '--accessAuthCode=${AuthCode}' ]
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PANEL_APP_PORT_HTTP}:6806
    volumes:
      - ${SIYUAN_ROOT_PATH}/workspace:/siyuan/workspace
    environment:
      - TZ=${Timezone:-Asia/Shanghai}
      - RUN_IN_CONTAINER=true
