version: "3"

networks:
  1panel-network:
    external: true

services:
  qinglong:
    image: whyour/qinglong:2.17.6
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ${QINGLONG_ROOT_PATH}/data:/ql/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:5700
    environment:
      - QlBaseUrl=${QINGLONG_BASE_URL}
