version: '3'

networks:
  1panel-network:
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2024-02-04T22-36-13Z
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PANEL_APP_PORT_HTTP}:9000
      - ${PANEL_APP_PORT_HTTP_API}:9001
    restart: always
    command: server /data --console-address :9000 --address :9001
    environment:
      MINIO_ROOT_USER: ${PANEL_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${PANEL_MINIO_ROOT_PASSWORD}
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    networks:
      - 1panel-network
    volumes:
      - ${MINIO_ROOT_PATH}/data:/data
    labels:
      createdBy: "Apps"
