version: "3"

networks:
  1panel-network:
    external: true

services:
  minio:
    image: ${MINIO_IMAGE}
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP:-9001}
      - ${PANEL_APP_PORT_API}:${MINIO_API:-9000}
    command: server
    environment:
      - MINIO_OPTS=--console-address :${PANEL_APP_PORT_HTTP:-9001} --address :${MINIO_API:-9000} --json
      - MINIO_VOLUMES=${MINIO_VOLUMES:-/data}
      - MINIO_API_ROOT_ACCESS=on
      - MINIO_ROOT_USER=${PANEL_MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${PANEL_MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_BROWSER=${MINIO_BROWSER:-on}
      - MINIO_BROWSER_LOGIN_ANIMATION=${MINIO_BROWSER_LOGIN_ANIMATION:-on}
      - MINIO_BROWSER_SESSION_DURATION=${MINIO_BROWSER_SESSION_DURATION:-12h}
      - MINIO_BROWSER_REDIRECT=true
      - MINIO_DOMAIN=${MINIO_DOMAIN}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      - ${MINIO_ROOT_PATH}/certs:/root/.minio/certs
      - ${MINIO_ROOT_PATH}/data:/data
