version: '3.7'

networks:
  1panel-network:
    external: true

services:
  speedtest:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/librespeed/speedtest:latest
    networks:
      - 1panel-network
    environment:
      MODE: standalone
      TITLE: ${SPEED_TEST_WEB_TITLE}
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ${SPEED_TEST_ROOT_PATH}/database:/database
    restart: always
    labels:
      createdBy: "Apps"
