version: "3.9"

networks:
  1panel-network:
    external: true

services:
  postgresql:
    image: tensorchord/pgvecto-rs:pg14-v0.2.1
    container_name: pg14-vectors-${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${POSTGRES_ROOT_PATH}:/var/lib/postgresql/data
