version: "3.8"

networks:
  1panel-network:
    external: true
  immich-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.33.22.0/24
          gateway: 172.33.22.1

name: immich

services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.101.0
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - immich-net
    volumes:
      - ${IMMICH_ROOT_PATH}/data/cache:/cache
    environment:
      NODE_ENV: ${NODE_ENV}
    env_file:
      - .env

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:v1.101.0
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - immich-net
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${IMMICH_ROOT_PATH}/data/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE_NAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DBINDEX: ${REDIS_DBINDEX}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.101.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
      - immich-net
    command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICH_ROOT_PATH}/data/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    environment:
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE_NAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DBINDEX: ${REDIS_DBINDEX}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
